apiVersion: v1
kind: Secret
metadata:
<<<<<<< HEAD
  namespace: default
  name: postgres-secret
=======
  name: postgres-secret
  namespace: default
>>>>>>> 721cd0175a59b9e27b92b67c49ad2a4420fa88a4
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=